### ISSUE TITLE
Crash Report Aether 1.7.10 when attempting to join servers

### ISSUE THREAD

**Issue by DogeTreats** [gildedgames/aether-issues#355]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/14/15 10:30 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at com.gildedgames.util.menu.MenuServices.fromGui(MenuServices.java:63)
	at com.gildedgames.util.menu.client.MenuClientEvents.onGuiOpen(MenuClientEvents.java:120)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_MenuClientEvents_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:775)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147258_a(NetHandlerPlayClient.java:570)
	at net.minecraft.network.play.server.S08PacketPlayerPosLook.func_148833_a(SourceFile:51)
	at net.minecraft.network.play.server.S08PacketPlayerPosLook.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.gildedgames.util.menu.MenuServices.fromGui(MenuServices.java:63)
	at com.gildedgames.util.menu.client.MenuClientEvents.onGuiOpen(MenuClientEvents.java:120)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_MenuClientEvents_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:775)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147258_a(NetHandlerPlayClient.java:570)
	at net.minecraft.network.play.server.S08PacketPlayerPosLook.func_148833_a(SourceFile:51)
	at net.minecraft.network.play.server.S08PacketPlayerPosLook.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiDownloadTerrain

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['DogeTreats'/7912, l='MpServer', x=-1062.50, y=88.62, z=1464.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-83,64,31), Chunk: (at 13,4,15 in -6,1; contains blocks -96,0,16 to -81,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['DogeTreats'/7912, l='MpServer', x=-1062.50, y=88.62, z=1464.50]]
	Retry entities: 0 total; []
	Server brand: cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 186320840 bytes (177 MB) / 291782656 bytes (278 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	aether{Alpha 1.7.10-1.0} [Aether II] (aether (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3355, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Custom Sky]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Fightr2021** [comment]
Oh god, the raw paste, it hurts. 
But, reinstall the Gilded Games util jar.

**Comment by Brenwwe** [comment]
Reinstall GGUil from http://go.aetherii.com/1KYyEAT
