### ISSUE TITLE
Server crashes on Startup [Can be closed]

### ISSUE THREAD

**Issue by Dragonisser** [gildedgames/aether-issues#367]
Well i have a modded server and put the aether mod + the util on it and now it crashes everytime when i try to start it.

The consoles also says it cant open the util because of an zipexception.
http://i.imgur.com/CkgH6gr.png

Time: 2/15/15 11:43 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/gildedgames/util/core/nbt/NBT
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: com.gildedgames.util.core.nbt.NBT
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 30 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.2.0-4-amd64
	Java Version: 1.7.0_76, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1946318472 bytes (1856 MB) / 2058878976 bytes (1963 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -Xmx8G -Xms2G -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 61 mods loaded, 61 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1232} [Forge Mod Loader] (1.7.10-1232.jar) Unloaded->Constructed
	Forge{10.13.2.1232} [Minecraft Forge] (1.7.10-1232.jar) Unloaded->Constructed
	appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	itemphysic{0.8.3} [ItemPhysic] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.3.72} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.72-universal.jar) Unloaded->Constructed
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed
	IC2{2.2.654-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed
	ImmibisCore{59.0.5} [Immibis Core] (immibis-core-59.0.5.jar) Unloaded->Constructed
	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed
	advcapes{1.2} [Advanced Capes] (advancedcapes-1.2.jar) Unloaded->Constructed
	aether{Alpha 1.7.10-1.0} [Aether II] (aether.jar) Unloaded
	appliedenergistics2{rv1-stable-1} [Applied Energistics 2] (appliedenergistics2-rv1-stable-1.jar) Unloaded
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded
	BuildCraft|Core{6.2.2} [BuildCraft] (buildcraft-6.2.2.jar) Unloaded
	BuildCraft|Transport{6.2.2} [BC Transport] (buildcraft-6.2.2.jar) Unloaded
	BuildCraft|Silicon{6.2.2} [BC Silicon] (buildcraft-6.2.2.jar) Unloaded
	BuildCraft|Builders{6.2.2} [BC Builders] (buildcraft-6.2.2.jar) Unloaded
	BuildCraft|Energy{6.2.2} [BC Energy] (buildcraft-6.2.2.jar) Unloaded
	BuildCraft|Factory{6.2.2} [BC Factory] (buildcraft-6.2.2.jar) Unloaded
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded
	DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2.jar) Unloaded
	Dynmap{2.1-104} [Dynmap] (Dynmap-2.1-forge-1.7.10.jar) Unloaded
	EnderStorage{1.4.5.26} [EnderStorage] (EnderStorage-1.7.10-1.4.5.26-universal.jar) Unloaded
	Forestry{3.2.0.5} [Forestry for Minecraft] (forestry_1.7.10-3.2.0.5.jar) Unloaded
	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded
	Mantle{1.7.10-0.3.1.jenkins180} [Mantle] (Mantle-mc1.7.10-0.3.1.jar) Unloaded
	millenaire{6.0.0} [Millénaire] (millenaire-6.0.0.jar) Unloaded
	MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct] (TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded
	mod_cobalt{1.5.6} [CobaltMod] (mod_cobalt-1.7.10-1.5.6.jar) Unloaded
	harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10c.jar) Unloaded
	PowerConverters{1.7.10-3.0.2.38} [Power Converters] (PowerConverters-1.7.10-3.0.2.38.jar) Unloaded
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded
	AS_Ruins{13.8} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded
	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Dragonisser** [comment]
Nvm can be closed. I dont know why but it downloaded 2 times a broken file.
