### ISSUE TITLE
Game freeze and crash after a trip to the aether and a few minutes in the overworld

### ISSUE THREAD

**Issue by Mistercl0ud** [gildedgames/aether-issues#380]
[18:59:42] [Server thread/INFO]: Saeldur has just earned the achievement [Leaving so soon?]
[18:59:42] [Client thread/INFO]: [CHAT] Saeldur has just earned the achievement [Leaving so soon?]
[18:59:43] [Server thread/WARN]: Strange packet type, ignoring LanteaPacket.UpdateRequest.
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ArrayIndexOutOfBoundsException: 3
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.aetherteam.aether.blocks.BlockWhiteGoldPillar.func_150163_b(BlockWhiteGoldPillar.java:58)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.block.BlockRotatedPillar.func_149691_a(SourceFile:65)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ConnectedTextures.isNeighbour(ConnectedTextures.java:769)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:600)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:342)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:219)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:122)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:80)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.RenderBlocks.func_147733_k(RenderBlocks.java:2955)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:338)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.updateRenderer(WorldRendererThreaded.java:186)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdateThread.run(WrUpdateThread.java:119)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalStateException: Already tesselating!
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.preRenderBlocksThreaded(WorldRendererThreaded.java:256)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.updateRenderer(WorldRendererThreaded.java:153)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdateThread.run(WrUpdateThread.java:119)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalStateException: Already tesselating!
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.preRenderBlocksThreaded(WorldRendererThreaded.java:256)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.updateRenderer(WorldRendererThreaded.java:153)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdateThread.run(WrUpdateThread.java:119)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalStateException: Already tesselating!
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.preRenderBlocksThreaded(WorldRendererThreaded.java:256)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.updateRenderer(WorldRendererThreaded.java:153)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdateThread.run(WrUpdateThread.java:119)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalStateException: Already tesselating!
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.preRenderBlocksThreaded(WorldRendererThreaded.java:256)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldRendererThreaded.updateRenderer(WorldRendererThreaded.java:153)
[19:00:17] [WrUpdateThread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WrUpdateThread.run(WrUpdateThread.java:119)

**Comment by Collin1971** [comment]
Does this issue occur without other mods?

**Comment by Collin1971** [comment]
This issue was fixed a few days ago by @115kino and I never updated the issue. Apologies! It's all fixed now I believe!
