### ISSUE TITLE
Server crash when a player leaves a dungeon by leaving the server.

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#387]
---- Minecraft Crash Report ----
// You're mean.

Time: 2/16/15 12:11 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.aetherteam.aether.client.gui.achievements.AchievementSoundHandler.playSoundfor(Lnet/minecraft/stats/Achievement;)V
	at net.aetherteam.aether.player.PlayerTracker.onAchievementActivated(PlayerTracker.java:37)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_PlayerTracker_onAchievementActivated_AchievementEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.player.EntityPlayerMP.func_71064_a(EntityPlayerMP.java:823)
	at net.aetherteam.aether.achievements.AetherAchievements.giveAchievement(AetherAchievements.java:70)
	at net.aetherteam.aether.player.PlayerAether.onChangedDimension(PlayerAether.java:586)
	at com.gildedgames.util.player.common.PlayerEventHandler.onChangedDimension(PlayerEventHandler.java:149)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_12_PlayerEventHandler_onChangedDimension_PlayerChangedDimensionEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerChangedDimensionEvent(FMLCommonHandler.java:545)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
	at net.aetherteam.aether.dungeons.Dungeon.teleportPlayerOutside(Dungeon.java:164)
	at net.aetherteam.aether.dungeons.Dungeon.leave(Dungeon.java:112)
	at net.aetherteam.aether.blocks.BlockSliderLabyrinthTotem.func_149727_a(BlockSliderLabyrinthTotem.java:79)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
	Memory: 132893632 bytes (126 MB) / 259522560 bytes (247 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util-1.7.10-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{Alpha 1.7.10-1.0} [Aether II] (aether (4).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 20; [EntityPlayerMP['roket333'/27368, l='world', x=285.91, y=31.00, z=8.26], EntityPlayerMP['Geolix'/35458, l='world', x=285.00, y=31.00, z=6.00]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by xJonL** [comment]
Is this singleplayer or multiplayer?

**Comment by roket333** [comment]
multiplayer


On Mon, Feb 16, 2015 at 12:35 PM, Jon <notifications@github.com> wrote:

> Is this singleplayer or multiplayer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/387#issuecomment-74561142>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png

**Comment by xJonL** [comment]
There is an issue with Aether achievements on multiplayer at the moment, it'll be fixed in the next patch. (Aether II 1.7.10-1.1) Thanks for the report. :heart_eyes:

**Comment by roket333** [comment]
you should add the achievement "Talc" for leaving a slider dungeon before completing it.
