### ISSUE TITLE
Config Request/Clarification: Continium orb output whitelist

### ISSUE THREAD

**Issue by GrinningMoon** [gildedgames/aether-issues#432]
I've been playing around with the Continium Orb, hoping to get a feel for what results/rewards you get for using it. I wanted to know what loot/crafting/smelting/all list the orb pulls from to select what it changes into. It seems to be pulling from crafting recipes, however I have gotten an Angry Enderman spawn egg (from Hardcore Ender Expansion) and a client crash which seems like the orb was attempting to pull an 'internal' item from Thaumic Horizons (a new addon to Thaumcraft). By internal, I mean that the item "ItemGolemPlacer" which I think is referencing the combined wand and thaumic horizons focus that is used to make temporary golems.

Anyways, to the point as I'm not reporting the crash but more options for the orb, could we please have a configuration option to define which items the Continium Orb can change into? Possibly, a blacklist/whitelist toggle and an area to define the items. Or maybe a config option that restricts the orb to only pull from available crafting/smelting recipes (HEE does this).

Snip from crash log for the curious:
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.kentington.thaumichorizons.common.items.ItemGolemPlacer.func_82790_a(ItemGolemPlacer.java:51)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:286)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:954)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1720)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Collin1971** [comment]
We're thinking on changing how the Continuum orb works. Perhaps make it grab from the list of available crafting recipes or dungeon loot (both Vanilla and the Aether's)?

**Comment by GrinningMoon** [comment]
I'd think that pulling from crafting/smelting recipes would work best. I know that thaumcraft 4 has loot sacks that pull from dungeon recipe lists and that works out fairly well because the sack outputs multiple items. The Continumm orb seems to be a 1 to 1 ratio. So players may be bummed if they get one of the filler items that spawn in dungeon chests.

**Comment by Collin1971** [comment]
Oops! Looks like I forgot to update this issue. I recently changed Continuums to use crafting and smelting recipes, and most of the Aether II items. It was originally getting all the IDs and choosing one at random. There will also be a configuration option for the Continuum.

This issue should be fixed in the next release. If not, feel free to re-open the issue!
