### ISSUE TITLE
I can't accualy pinpoint the cause in this crash

### ISSUE THREAD

**Issue by roket333** [gildedgames/aether-issues#433]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/25/15 5:08 PM
Description: Ticking entity

io.netty.handler.codec.EncoderException: java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to java.lang.Short
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at cpw.mods.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:48)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:158)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:569)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:434)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:338)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:382)
	at net.minecraft.world.World.func_72866_a(World.java:2643)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2596)
	at net.minecraft.world.World.func_72939_s(World.java:2408)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to java.lang.Short
	at net.minecraft.entity.DataWatcher.func_151510_a(SourceFile:220)
	at net.minecraft.entity.DataWatcher.func_151509_a(SourceFile:186)
	at cpw.mods.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:189)
	at cpw.mods.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:22)
	at cpw.mods.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:11)
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at cpw.mods.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:48)
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:158)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:569)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:434)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:338)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:382)
	at net.minecraft.world.World.func_72866_a(World.java:2643)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2596)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 746
	Entity Name: Geolix
	Entity's Exact location: -453.25, 54.74, 344.25
	Entity's Block location: World: (-454,54,344), Chunk: (at 10,3,8 in -29,21; contains blocks -464,0,336 to -449,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2408)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: DIM3
	All players: 3 total; [EntityPlayerMP['roket333'/115, l='DIM3', x=-301.73, y=56.30, z=-122.59](roket333 at -301.73236789493683,56.29912009031627,-122.58838311614312), EntityPlayerMP['ggamer16'/736, l='DIM3', x=-501.62, y=42.00, z=509.40](ggamer16 at -501.61592063555537,42.0,509.3993717737932), EntityPlayerMP['Geolix'/746, l='DIM3', x=-453.25, y=54.74, z=344.25](Geolix at -453.2495424448294,54.739362540383404,344.25340920786175)]
	Chunk stats: ServerChunkCache: 1126 Drop: 0
	Level seed: 1323772445839816641
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-470,43,343), Chunk: (at 10,2,7 in -30,21; contains blocks -480,0,336 to -465,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 544876 game time, 96000 day time
	Level dimension: 3
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 50617 (now: false), thunder time: 10760 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2135386960 bytes (2036 MB) / 2678063104 bytes (2554 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xms2G -Xmx4G -XX:MaxPermSize=128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.25.1207} [Forge Mod Loader] (server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.0.1207} [Minecraft Forge] (server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{Alpha 1.7.10-1.1} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 3 / 50; [EntityPlayerMP['roket333'/115, l='DIM3', x=-301.73, y=56.30, z=-122.59](roket333 at -301.73236789493683,56.29912009031627,-122.58838311614312), EntityPlayerMP['ggamer16'/736, l='DIM3', x=-501.62, y=42.00, z=509.40](ggamer16 at -501.61592063555537,42.0,509.3993717737932), EntityPlayerMP['Geolix'/746, l='DIM3', x=-453.25, y=54.74, z=344.25](Geolix at -453.2495424448294,54.739362540383404,344.25340920786175)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Collin1971** [comment]
What appears to be happen is as follows:

- The server sends a packet to the client, with a itemstack instead of a number (specifically, a short)
- The client receives the packet and tries to parse it.
- The client expects a number, but the sent code doesn't contain a number, it contains an itemstack.
- The client has no clue it's an itemstack, and tries reading it as a number.
- Because you can't read an itemstack as a number, an exception is thrown and crashes the client.

Debugging these issues are a bit more complicated in my experience than regular crashes. Do you have any details about _when_ this happens?

**Comment by Collin1971** [comment]
It seems that the client is trying to send a packet to the server with an itemstack, when the packet requires a short. Because that's not possible (as far as I know) it's throwing an exception and vomiting all over itself (crashing). Do you have _any_ details on when this happens?

This could also be a _vanilla bug_ judging by the crashlog:
```
cpw.mods.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:158)
at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:569)
at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:434)
```

**Comment by roket333** [comment]
It happened when me and my friends where doing the "Rocket Jump" glitch in
creative with the hammer of notch.
The "Rocket Jump" glitch is using the no cooldown bar in creative as an
advantage and spamming the hammer of notch under you. because of the
pushback coded in, this creates what is similar to a Rocket jump, hence the
name.

On Fri, Feb 27, 2015 at 3:06 PM, Collin Soares <notifications@github.com>
wrote:

> It seems that the client is trying to send a packet to the server with an
> itemstack, when the packet requires a short. Because that's not possible
> (as far as I know) it's throwing an exception and vomiting all over itself
> (crashing). Do you have *any* details on when this happens?
>
> This could also be a *vanilla bug* judging by the crashlog:
>
> cpw.mods.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:158)
> at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:569)
> at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:434)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gildedgames/aether-issues/issues/433#issuecomment-76480976>
> .
>



-- 
http://signaturecraft.us/signatures/eJwrs9OLcnNzEtNLkpMK0kt4ipCE3BIz03MzNFLzs-FSBkbG3OFpCbmKrjlF5UUpRYXKxhxBZfmFWUWp3IZmZqCsQGXAQDJYh4C.png
