### ISSUE TITLE
Altar Sever Crash

### ISSUE THREAD

**Issue by Renari** [gildedgames/aether-issues#461]
This seems to have put the server into a crash loop the only other mention of this I see is #409 which is close. Is this already fixed for the next update?
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 3/8/15 12:58 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.aetherteam.aether.tile_entities.TileEntityAltar.func_145845_h(TileEntityAltar.java:477)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.tile_entities.TileEntityAltar.func_145845_h(TileEntityAltar.java:477)

-- Block entity being ticked --
Details:
	Name: Altar // net.aetherteam.aether.tile_entities.TileEntityAltar
	Block type: ID #237 (tile.altar // net.aetherteam.aether.blocks.BlockAltar)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-749,80,457), Chunk: (at 3,5,9 in -47,28; contains blocks -752,0,448 to -737,255,463), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Actual block type: ID #237 (tile.altar // net.aetherteam.aether.blocks.BlockAltar)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['OverlordKyo'/4142238, l='world', x=-746.50, y=80.00, z=454.05], EntityPlayerMP['Renari'/3761952, l='world', x=-748.04, y=80.00, z=456.18]]
	Chunk stats: ServerChunkCache: 781 Drop: 0
	Level seed: -454802827
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-784,64,944), Chunk: (at 0,4,0 in -49,59; contains blocks -784,0,944 to -769,255,959), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 3523086 game time, 88536 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 104710 (now: false), thunder time: 158125 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.10.23-xxxx-std-ipv6-64
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1035518264 bytes (987 MB) / 4234674176 bytes (4038 MB) up to 4234674176 bytes (4038 MB)
	JVM Flags: 4 total; -Xmx4096M -Xms4096M -XX:PermSize=256m -XX:MaxPermSize=512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 77 mods loaded, 77 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (permgen.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (permgen.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SC0_SpaceCore{0.7.13} [SpaceCore] ([1.7.10] SpaceCore 0.7.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SC0_UsefulPets{1.2.4} [Useful Pets] ([1.7.10] Useful Pets 1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DC1{3.4.2.19} [KingCore] ([1.7.2+] KingCore v3.4.2.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FishingNets{1.2.1.5} [Fishing Nets] ([1.7.10M] FishingNets v1.2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	bdlib{1.6.5.52} [BD Lib] (bdlib-mc1710-1.6.5.52.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ae2stuff{0.1.6.14} [AE2 Stuff] (ae2stuff-mc1710-0.1.6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{Alpha 1.7.10-1.1} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AetherAspects{Alpha 1.7.10-1.1} [Aether Aspects] (AetherAspects-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Botania{r1.5-168} [Botania] (Botania r1.5-168.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC5} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC5-207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.4.2} [BuildCraft] (buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.4.2} [BC Transport] (buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.4.2} [BC Silicon] (buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.4.2} [BC Builders] (buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.4.2} [BC Energy] (buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.4.2} [BC Factory] (buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	extracells{2.2.56} [ExtraCells] (ExtraCells-1.7.10-2.2.56b86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForbiddenMagic{1.7.10-0.51} [Forbidden Magic] (Forbidden Magic-1.7.10-0.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-The Journey (4.2.2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	JABBA{1.2.0b} [JABBA] (Jabba-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons{1.12.4.16} [NEI Addons] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Botany{1.12.4.16} [NEI Addons: Botany] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|Forestry{1.12.4.16} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|CraftingTables{1.12.4.16} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NEIAddons|ExNihilo{1.12.4.16} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.4.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.5.13.65} [ProjectRed] (ProjectRed-1.7.10-4.5.13.65-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SSTOW{RC7-A} [Soul Shards: The Old Ways] (SSTOW-1.7.10-RC7-A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thaumicenergistics{0.8.9.0b-rv2} [Thaumic Energistics] (thaumicenergistics-0.8.9.0b-rv2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThaumicHorizons{1.0} [Thaumic Horizons] (thaumichorizons-1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	thaumicinfusion{3.966} [Thaumic Infusion] (ThaumicInfusion-3.966.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	erebus{0.2pre12} [Erebus] (TheErebus-0.2pre12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalDynamics{1.7.10R1.0.0RC5} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC5-94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0RC5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC5-137.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.4} [The Twilight Forest] (twilightforest-1.7.10-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenModsLib crash transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:FINISHED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
	AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.0.0RC5-207
	ThermalFoundation: -[1.7.10]1.0.0RC4-58
	ThermalDynamics: -[1.7.10]1.0.0RC5-94
	ThermalExpansion: -[1.7.10]4.0.0RC5-137
	List of loaded APIs: 
		* API_NEK (1.0.0) from NotEnoughKeys-1.7.10-1.0.0b29.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-beta-8.jar
		* Baubles|API (1.0.1.4) from Reliquary-1.2.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
		* BotaniaAPI (35) from Botania r1.5-168.jar
		* BuildCraftAPI|blueprints (1.2) from buildcraft-6.4.2.jar
		* BuildCraftAPI|boards (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|core (1.4) from buildcraft-6.4.2.jar
		* BuildCraftAPI|events (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|facades (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|filler (3.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|gates (4.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|items (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|power (1.3) from buildcraft-6.4.2.jar
		* BuildCraftAPI|recipes (2.1) from buildcraft-6.4.2.jar
		* BuildCraftAPI|robots (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|statements (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|tiles (1.1) from buildcraft-6.4.2.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-6.4.2.jar
		* BuildCraftAPI|transport (4.0) from buildcraft-6.4.2.jar
		* CoFHAPI (1.7.10R1.0.1) from buildcraft-6.4.2.jar
		* CoFHAPI|block (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|core (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|energy (1.7.10R1.0.1) from buildcraft-6.4.2.jar
		* CoFHAPI|fluid (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|inventory (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|item (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|tileentity (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|transport (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHAPI|world (1.7.10R1.0.9) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|audio (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui|container (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui|element (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|gui|slot (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|inventory (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|render (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|render|particle (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|util (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|util|helpers (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|util|position (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|world (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* CoFHLib|world|feature (1.7.10R1.0.0RC5) from CoFHCore-[1.7.10]3.0.0RC5-207.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 48; [EntityPlayerMP['OverlordKyo'/4142238, l='world', x=-746.50, y=80.00, z=454.05], EntityPlayerMP['Renari'/3761952, l='world', x=-748.04, y=80.00, z=456.18]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Renari** [comment]
Says update planed in next update in #441.
