### ISSUE TITLE
Null Pointer at runtime

### ISSUE THREAD

**Issue by Termin8or** [gildedgames/aether-issues#500]
java.lang.NullPointerException
at net.aetherteam.aether.client.RenderPlayerAether.doRenderMisc(RenderPlayerAether.java:401)
at net.aetherteam.aether.client.RenderPlayerAether.renderMisc(RenderPlayerAether.java:224)
at net.aetherteam.aether.client.RenderPlayerAether.func_76986_a(RenderPlayerAether.java:75)
at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
at bspkrs.client.util.EntityUtils.drawEntityOnScreen(EntityUtils.java:186)
at bspkrs.bspkrscore.fml.BSMainMenuRenderTicker.onTick(BSMainMenuRenderTicker.java:108)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_882_BSMainMenuRenderTicker_onTick_RenderTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Spams chat constantly during runtime Forge 1408

**Comment by 115kino** [comment]
should be fixed in the 1.5 update although this issue is unexplained. (If this issue does pop-up in the 1.5 update, feel free to re-open it)
