### ISSUE TITLE
Launcher can't open 2 Minecraft's at the same time:

### ISSUE THREAD

**Issue by ItzDennisz** [gildedgames/aether-issues#550]
java.nio.file.FileSystemException: C:\Users\marian\AppData\Roaming\.aether\profiles\1.7.10-1.5.1\mods\aether.jar: Het proces heeft geen toegang tot het bestand omdat het door een ander
proces wordt gebruikt.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.nio.file.Files.copy(Unknown Source)
	at net.aetherteam.aether.launcher.GameLauncher.launchGame(GameLauncher.java:186)
	at net.aetherteam.aether.launcher.GameLauncher.onDownloadJobFinished(GameLauncher.java:456)
	at net.aetherteam.aether.launcher.download.DownloadJob.popAndDownload(DownloadJob.java:138)
	at net.aetherteam.aether.launcher.download.DownloadJob.access$0(DownloadJob.java:111)
	at net.aetherteam.aether.launcher.download.DownloadJob$1.run(DownloadJob.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by xJonL** [comment]
This is not a bug intentional the way your operating system works. Cannot launch multiple instances if they're being used
