### ISSUE TITLE
 AetherII Server Crash

### ISSUE THREAD

**Issue by THHakureiReimu** [gildedgames/aether-issues#595]
Crash Report
=============================================
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/26/15 4:37 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.aetherteam.aether.entities.bosses.EntityLabyrinthEye.spawnLargeCog(EntityLabyrinthEye.java:183)
	at net.aetherteam.aether.entities.bosses.EntityLabyrinthEye.func_70785_a(EntityLabyrinthEye.java:123)
	at net.aetherteam.aether.entities.bosses.EntityLabyrinthEye.func_70071_h_(EntityLabyrinthEye.java:289)
	at net.minecraft.world.World.func_72866_a(World.java:2643)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:2596)
	at net.minecraft.world.World.func_72939_s(World.java:2409)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.aetherteam.aether.entities.bosses.EntityLabyrinthEye.spawnLargeCog(EntityLabyrinthEye.java:183)
	at net.aetherteam.aether.entities.bosses.EntityLabyrinthEye.func_70785_a(EntityLabyrinthEye.java:123)
	at net.aetherteam.aether.entities.bosses.EntityLabyrinthEye.func_70071_h_(EntityLabyrinthEye.java:289)
	at net.minecraft.world.World.func_72866_a(World.java:2643)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:2596)

-- Entity being ticked --
Details:
	Entity Type: aether.labyrinthEye (net.aetherteam.aether.entities.bosses.EntityLabyrinthEye)
	Entity ID: 1026691
	Entity Name: Labyrinth Eye
	Entity's Exact location: 10523.49, 29.46, 18.00
	Entity's Block location: World: (10523,29,18), Chunk: (at 11,1,2 in 657,1; contains blocks 10512,0,16 to 10527,255,31), Region: (20,0; contains chunks 640,0 to 671,31, blocks 10240,0,0 to 10751,255,511)
	Entity's Momentum: -0.38, 0.37, -0.12
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2409)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)

-- Affected level --
Details:
	Level name: DIM4
	All players: 2 total; [EntityPlayerMP['LXA68'/814547, l='DIM4', x=10374.54, y=31.00, z=8.10](LXA68 at 10374.541793208788,31.0,8.102046076385804), EntityPlayerMP['Aies'/1032744, l='DIM4', x=10526.44, y=30.00, z=22.05](Aies at 10526.444151681018,30.0,22.04979520913284)]
	Chunk stats: ServerChunkCache: 238 Drop: 136
	Level seed: -2041548997528397279
	Level generator: ID 04 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13608703 game time, 13608703 day time
	Level dimension: 4
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30083 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 377619568 bytes (360 MB) / 1973944320 bytes (1882 MB) up to 6203899904 bytes (5916 MB)
	JVM Flags: 1 total; -Xmx6656M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 38
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 30 mods loaded, 30 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.114.1388} [Forge Mod Loader] (MCPC-Plus.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1403} [Minecraft Forge] (MCPC-Plus.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util-1.7.10-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{1.7.10-1.5.2} [Aether II] (aether-1.7.10-1.5.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AetherAspects{Alpha 1.7.10-1.2} [Aether Aspects] (AetherAspects-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	betterrecords{@VERSION@} [Better Records] (BetterRecords-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	buffedtools{1.1.1710.1} [Buffed Tools] (BuffedTools-1.1.1710.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cwm{3.0} [Catoon Weapons Mod] (Cartoon Weapons-V3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cosmeticWings{0.4.2} [Cosmetic Wings] (Cosmetic-Wings-1.7.10-0.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.16 mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Emotes{1.0} [Emotes] (Emotes 1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	emeraldtools{Release 1} [Emerald Tools & Armor] (Grimmreepers Emerald Tools & Armor-[1.7.10]-R1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ingameconfigmanager{0.1} [InGameConfigManager] (InGameConfigManager Alpha v0.1.9 mc1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MoreBows2{1.2} [More Bows 2] (MoreBows2-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.257.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RTG{0.1.0} [Realistic Terrain Generation] (RTG-1.7.10-0.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialMobs{3.2.1} [Special Mobs] (SpecialMobs-1.7.10-3.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	twintails{1.0.3} [TwinTails] (twintails-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UndergroundBiomes{0.7} [Underground Biomes Constructs] (UndergroundBiomesConstructs-1.7.2-0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UsefulFood{1.5.0} [UsefulFood] (UsefulFood-1.5.0-CN-By-Dark.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	weaponcaseloot{1.0.6} [WeaponCaseLoot] (weaponcaseloot-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DummyCore{1.11} [DummyCore] (DummyCorev1.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 22 / 30; [EntityPlayerMP['Xue_Shang'/907973, l='world', x=1797.93, y=71.00, z=-3269.06](Xue_Shang at 1797.9335905233834,71.0,-3269.0584647379774), EntityPlayerMP['Henry'/736065, l='world', x=-1006.15, y=65.00, z=680.42](Henry at -1006.149106104885,65.0,680.4179908475961), EntityPlayerMP['Exe'/623348, l='world', x=-4348.76, y=65.00, z=-4209.85](Exe at -4348.758748642338,65.0,-4209.846560596621), EntityPlayerMP['Hentai_Luck'/864569, l='world', x=-2640.75, y=63.00, z=1284.26](Hentai_Luck at -2640.7505849015915,63.0,1284.2615122690027), EntityPlayerMP['fanizan'/852508, l='world', x=2240.30, y=73.00, z=-1432.86](fanizan at 2240.300000011921,73.0,-1432.8577517978224), EntityPlayerMP['dd3'/940470, l='world', x=4161.81, y=63.00, z=-4083.32](dd3 at 4161.81048770537,63.0,-4083.317131559598), EntityPlayerMP['Implicit_Ayano'/942949, l='world', x=2215.60, y=72.00, z=-1447.16](Implicit_Ayano at 2215.6000400286757,72.0,-1447.158335379576), EntityPlayerMP['Guogai'/1032410, l='DIM3', x=8002.11, y=73.00, z=7.47](Guogai at 8002.113915305465,73.0,7.467472198553954), EntityPlayerMP['0024'/1032696, l='DIM7', x=2229.36, y=35.00, z=1981.99](0024 at 2229.3647846272265,35.0,1981.9883728017226), EntityPlayerMP['Again'/1032697, l='world', x=2783.50, y=63.00, z=-3313.50](Again at 2783.5,63.0,-3313.5), EntityPlayerMP['LXA68'/814547, l='DIM4', x=10374.54, y=31.00, z=8.10](LXA68 at 10374.541793208788,31.0,8.102046076385804), EntityPlayerMP['kesang'/1033103, l='world', x=-2660.49, y=63.00, z=1270.82](kesang at -2660.489284713076,63.0,1270.8203836946543), EntityPlayerMP['jj_guai'/1033301, l='spawn', x=-405.05, y=188.00, z=-691.40](jj_guai at -405.04950675761165,188.0,-691.3953299508768), EntityPlayerMP['Implicit_Meng7'/825333, l='DIM3', x=2455.65, y=57.00, z=-1326.72](Implicit_Meng7 at 2455.6450082869374,57.0,-1326.7161145873001), EntityPlayerMP['Implicit_Ene'/961543, l='world', x=2214.93, y=73.00, z=-1444.05](Implicit_Ene at 2214.927107206569,73.0,-1444.0490216474693), EntityPlayerMP['Cream_9'/954919, l='world', x=4275.90, y=70.00, z=-4524.86](Cream_9 at 4275.896293393797,70.0,-4524.855659231849), EntityPlayerMP['YensOneP'/1014023, l='DIM7', x=-2558.30, y=10.00, z=-1462.34](YensOneP at -2558.300000011921,10.0,-1462.3405198262217), EntityPlayerMP['nmbd'/1032991, l='world', x=3415.21, y=176.00, z=3857.91](nmbd at 3415.209143431258,176.0,3857.914057924225), EntityPlayerMP['Zxxx'/1034852, l='spawn', x=-434.44, y=188.00, z=-701.45](Zxxx at -434.4430087506114,188.0,-701.450603436368), EntityPlayerMP['super_hqx'/1033121, l='DIM7', x=-2558.46, y=10.00, z=-1463.31](super_hqx at -2558.461149341792,10.0,-1463.3074010098599), EntityPlayerMP['Aies'/1032744, l='DIM4', x=10526.44, y=30.00, z=22.05](Aies at 10526.444151681018,30.0,22.04979520913284), EntityPlayerMP['AB_CD'/1034221, l='world', x=-3730.50, y=74.00, z=-1301.50](AB_CD at -3730.5,74.0,-1301.5)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by xJonL** [comment]
Hey there, can you reproduce the crash on the latest version of our mod? :smile:

**Comment by Lachney** [comment]
Related Issue with AOS:
https://gist.github.com/24b39045ce1b5423242962095705dd70
