### ISSUE TITLE
Crash report, how to fix?

### ISSUE THREAD

**Issue by koolkid1** [gildedgames/aether-issues#633]
[Crash log](https://gist.github.com/Collin1971/5453bef7c66224db24c288709fe9e08e) (moved to Gist by @Collin1971)

**Comment by Collin1971** [comment]
_Please_ try updating Forge to build `1558`.

**Comment by koolkid1** [comment]
[Crash log](https://gist.github.com/Collin1971/dfd0fc6a653361fff22de0457f4c933d) (moved to Gist by @Collin1971)

**Comment by Collin1971** [comment]
>  Caused by: java.lang.ClassNotFoundException: com.gildedgames.util.io_manager.io.IOSyncable

You're using an old version of Gilded Games Utility. Please download the latest version from [here](http://aetherii.com/downloads).

**Comment by koolkid1** [comment]
ty Collin, also my world is crashing when I open it, any way to fix?

**Comment by koolkid1** [comment]
[Crash log](https://gist.github.com/Collin1971/49a8c13baad8b7566e90610ddab14089) (moved to Gist by @Collin1971)

**Comment by koolkid1** [comment]
it launched just the world is glitched

**Comment by koolkid1** [comment]
worlds are not launching

**Comment by koolkid1** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/8/16 9:59 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
    at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
    at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
    Level name: MpServer
    All players: 0 total; []
    Chunk stats: MultiplayerChunkCache: 0, 0
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 0 total; []
    Retry entities: 0 total; []
    Server brand: ~~ERROR~~ NullPointerException: null
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 289307800 bytes (275 MB) / 890073088 bytes (848 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 76 mods loaded, 67 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.74} [Not Enough Items](Not-Enough-Items-1.7.10.jar) 
    UCHIJAAAA   se{0.4.1} [Super Enchants](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.6} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) 
    UCHIJAAAA   gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar) 
    UCHIJAAAA   FLabsBF{4.3} [Better Furnaces]([1.7.10]Better_Furnaces_V4.3.jar) 
    UCHIJAAAA   DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJAAAA   BuildCraft|Core{6.1.5} [BuildCraft](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCHIJAAAA   BuildCraft|Builders{6.1.5} [BC Builders](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCHIJAAAA   BuildCraft|Transport{6.1.5} [BC Transport](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCHIJAAAA   BuildCraft|Silicon{6.1.5} [BC Silicon](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCHIJAAAA   BuildCraft|Factory{6.1.5} [BC Factory](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCHIJAAAA   BuildCraft|Energy{6.1.5} [BC Energy](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCHIJAAAA   adminweapons{1.0} [Admin Weapons](adminweapons-v1-mc1.7.10.jar) 
    UCHIJAAAA   aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   Backpack{2.0.1} [Backpack](Backpacks-Mod.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   BiblioCraft{1.7.3} [BiblioCraft](BiblioCraft-Mod-1.7.10.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   chancecubes{1.7.10-1.6.2.72} [Chance Cubes](ChanceCubes-1.7.10-1.6.2.72.jar) 
    UCHIJAAAA   EE3{0.3.507} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.507.jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) 
    UCHIJAAAA   eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.4b} [Extra Utilities](extrautilities-1.2.4b.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAA   Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCHIJAAAA   headcrumbs{1.2.5} [Headcrumbs](Headcrumbs-Mod-1.7.10.jar) 
    UCHIJAAAA   IC2{2.2.791-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UCHIJAAAA   InventoryPets{1.4.0} [Inventory Pets](inventorypets-1.7.10-1.4.0-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   jaff{1.4.1_for_1.7.10} [Just a Few Fish](JustAFewFish-1.4.1_for_1.7.10.jar) 
    UCHIJAAAA   legends{1.4} [Legends Mod](Legends Core-1.4.jar) 
    UCHIJAAAA   lootplusplus{0.22_for_1.7} [Loot++](Loot++-0.22_for_1.7.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJAAAA   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHIJAAAA   OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-268.jar) 
    UCHIJAAAA   OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-512.jar) 
    UCHIJAAAA   OreSpawn{1.7.10.20.3} [OreSpawn](orespawn-1.7.10-20.3.zip) 
    UCHIJAAAA   PortalGun{4.0.0-beta-2} [PortalGun](Portal-Gun-Mod-1.7.10.jar) 
    UCHIJAAAA   HeroSuits{1.2} [Project Superhuman](ProjectSuperhuman - v1.2 - 1.7.10.jar) 
    UCHIJAAAA   RainbowWorld{1.0.0} [RainbowWorld](Rainbow World %281.7.10%29.jar) 
    UCHIJAAAA   ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJAAAA   transformers{0.5.0} [Transformers Mod](Transformers-1.7.10-0.5.1.jar) 
    UCHIJAAAA   lucky{5.1.0} [Lucky Block](z[1-7-10]_Lucky_Block_v5-1-0.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    CoFHCore: -[1.7.10]3.1.2-325
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    ThermalFoundation: -[1.7.10]1.2.3-112
    Mantle Environment: Environment healthy.
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    ThermalExpansion: -[1.7.10]4.1.2-240
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Collin1971** [comment]
You still haven't removed CoFH or OpenModsLib to narrow it down. _Please_ remove the mods and upload a new crash log to [GitHub's Gist](https://gist.github.com).
