### ISSUE TITLE
crash upon hitting entity

### ISSUE THREAD

**Issue by enderplayer2001** [gildedgames/aether-issues#635]
i did several tests and there are only 2 possibilities for me to solve it: 
1 remove littlemaidmob mod
2 remove aether mod

it happens whenever i try to kill a little maid from the little maid mob mod. NO i'm not using outdated versions and NOT its not another mod, i tested it mod by mod.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/04/16 17:10
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at net.aetherteam.aether.player.PlayerAether.wearingArmour(PlayerAether.java:713)
    at net.aetherteam.aether.player.PlayerAether.wearingPhoenixArmour(PlayerAether.java:746)
    at net.aetherteam.aether.player.abilities.AbilityArmor.onLivingAttack(AbilityArmor.java:180)
    at net.aetherteam.aether.player.PlayerAether.onLivingAttack(PlayerAether.java:450)
    at net.aetherteam.aether.player.PlayerEventHandler.onLivingAttack(PlayerEventHandler.java:126)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_273_PlayerEventHandler_onLivingAttack_LivingHurtEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:298)
    at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1080)
    at net.minecraft.entity.player.EntityPlayerMP.localDamageEntity(EntityPlayerMP.java)
    at api.player.server.ServerPlayerAPI.damageEntity(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.func_70665_d(EntityPlayerMP.java)
    at littleMaidMobX.LMM_EntityLittleMaidAvatarMP.W_damageEntity(LMM_EntityLittleMaidAvatarMP.java:604)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70665_d(LMM_EntityLittleMaid.java:1444)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:785)
    at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:145)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70097_a(LMM_EntityLittleMaid.java:1511)
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
    at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java)
    at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.aetherteam.aether.player.PlayerAether.wearingArmour(PlayerAether.java:713)
    at net.aetherteam.aether.player.PlayerAether.wearingPhoenixArmour(PlayerAether.java:746)
    at net.aetherteam.aether.player.abilities.AbilityArmor.onLivingAttack(AbilityArmor.java:180)
    at net.aetherteam.aether.player.PlayerAether.onLivingAttack(PlayerAether.java:450)
    at net.aetherteam.aether.player.PlayerEventHandler.onLivingAttack(PlayerEventHandler.java:126)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_273_PlayerEventHandler_onLivingAttack_LivingHurtEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:298)
    at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1080)
    at net.minecraft.entity.player.EntityPlayerMP.localDamageEntity(EntityPlayerMP.java)
    at api.player.server.ServerPlayerAPI.damageEntity(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.func_70665_d(EntityPlayerMP.java)
    at littleMaidMobX.LMM_EntityLittleMaidAvatarMP.W_damageEntity(LMM_EntityLittleMaidAvatarMP.java:604)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70665_d(LMM_EntityLittleMaid.java:1444)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:785)
    at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:145)
    at littleMaidMobX.LMM_EntityLittleMaid.func_70097_a(LMM_EntityLittleMaid.java:1511)
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
    at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java)
    at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@1bfd29f8
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 388554368 bytes (370 MB) / 641728512 bytes (612 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 53 mods loaded, 53 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1566} [Minecraft Forge](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   OldModelLoader{1.0} [OldModelLoader](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.105} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.105-universal.jar) 
    UCHIJAAAA   PlayerAPI{1.3} [Player API](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.7} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) 
    UCHIJAAAA   gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8b.jar) 
    UCHIJAAAA   aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar) 
    UCHIJAAAA   armourersWorkshop{1.7.10-0.38.1.98} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.38.1.98.jar) 
    UCHIJAAAA   plushieWrapper{0.0.0} [Plushie Wrapper](Armourers-Workshop-1.7.10-0.38.1.98.jar) 
    UCHIJAAAA   Artifacts{1.1.3} [Artifacts](Artifacts-1.1.3.jar) 
    UCHIJAAAA   BiblioCraft{1.9.2} [BiblioCraft](BiblioCraft[v1.9.2][MC1.7.10].jar) 
    UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   customnpcs{1.7.10b} [CustomNpcs](CustomNPCs_1.7.10b.jar) 
    UCHIJAAAA   OmnisCore{0.1.0} [Omnis Core](OmnisCore-1.7.10 - 0.0.6-universal.jar) 
    UCHIJAAAA   dimensionalPockets{0.11.4.1} [Dimensional Pockets](DimensionalPockets-1.7.10-0.11.4.1-universal.jar) 
    UCHIJAAAA   DragonMounts{r41-1.7.10} [Dragon Mounts](DragonMounts-r41-1.7.10.jar) 
    UCHIJAAAA   dualhotbar{1.6} [Dual Hotbar](dualhotbar-1.7.10-1.6.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   EnderTech{1.7.10-0.3.2.375} [EnderTech](EnderTech-1.7.10-0.3.2.375.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   grim3212core{V0.2 - 1.7.10} [Grim3212 Core](Grim3212-Core-1.7.10.jar) 
    UCHIJAAAA   HexxitGear{0.03} [HexxitGear](Hexxit Gear 2 0.03.jar) 
    UCHIJAAAA   InventoryPets{1.4.0} [Inventory Pets](inventorypets-1.7.10-1.4.0-universal.jar) 
    UCHIJAAAA   lmmx{1.0} [lmmx](littleMaidMobX-1.7.x_0.1.1.jar) 
    UCHIJAAAA   MMMLibX{1.7.x-srg-1} [MMMLibX](littleMaidMobX-1.7.x_0.1.1.jar) 
    UCHIJAAAA   zabuton{1.0} [zabuton](littleMaidMobX-1.7.x_0.1.1.jar) 
    UCHIJAAAA   AS_Minions{1.9.4} [Minions](Minions-1.7.10.jar) 
    UCHIJAAAA   MultiPageChest{1.3.4} [Multi Page Chest](MultiPageChest-1.3.4-MC1.7.10.jar) 
    UCHIJAAAA   OpenMods{0.7} [OpenMods](OpenModsLib-1.7.10-0.7.jar) 
    UCHIJAAAA   OpenBlocks{1.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.jar) 
    UCHIJAAAA   harvestcraft{1.7.10i} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10i.jar) 
    UCHIJAAAA   secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.411.jar) 
    UCHIJAAAA   SlimevoidLib{2.0.4.7} [Slimevoid Library](SlimevoidLibrary-2.0.4.7.jar) 
    UCHIJAAAA   alfheimwings{30} [The Wings of Alfheim](The Wings of Alfheim-1.7.10-30 %281%29.jar) 
    UCHIJAAAA   THKaguyaMod{2.76_1.7.10} [Itutu no Nandai MOD+](Touhou-Items-Mod-1.7.10.zip) 
    UCHIJAAAA   AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   wawla{1.2.1} [What Are We Looking At](Wawla-1.2.1_1.7.10.jar) 
    UCHIJAAAA   WiiRemoteId{1.1} [WiiRemoteMod by Nether(Miko3335)](WiiMod-1.7.10-1.1.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    DPAnalytics Crash Check: Will analyze crash-log before shutdown and send it to the Dimensional Pockets developer
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['enderplayer2001'/117, l='New Worldaw r w r   sss  s s ss', x=-1592,79, y=4,00, z=-327,24]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Collin1971** [comment]
Issues like these have been fixed in the Aether 1.8 codebase, but will not be backported to Minecraft 1.7 as they require _massive_ changes.
