### ISSUE TITLE
Known Compatibility Issues Discovered

### ISSUE THREAD

**Issue by Kusorai** [gildedgames/aether-issues#637]
This mod will not work with either Minecraft Comes Alive nor will it allow you to use Tropicraft.

**Comment by Collin1971** [comment]
Telling us that it just "doesn't work" helps nobody. Please provide _relevant_ details such as crash logs and specific bugs.

**Comment by Kusorai** [comment]
That's the issue is that for some reason it's always client side never server side. I should have mentioned that first off. My little brother isn't very computer literate and it's difficult to get the details from him so if I can I'll post here.

**Comment by Kusorai** [comment]
OK so found this
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/20/16 12:48 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.meteor.common.tileentity.TileEntityMeteorShield.onChunkUnload(TileEntityMeteorShield.java:469)
    at net.minecraft.world.World.func_72939_s(World.java:1979)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.meteor.common.tileentity.TileEntityMeteorShield.onChunkUnload(TileEntityMeteorShield.java:469)
    at net.minecraft.world.World.func_72939_s(World.java:1979)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['oOSpiderdogoO'/52337, l='MpServer', x=739.50, y=71.62, z=170.50]]
    Chunk stats: MultiplayerChunkCache: 5, 5
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (734,65,173), Chunk: (at 14,4,13 in 45,10; contains blocks 720,0,160 to 735,255,175), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
    Level time: 3060855 game time, 9566 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 5 total; [EntityClientPlayerMP['oOSpiderdogoO'/52337, l='MpServer', x=739.50, y=88.62, z=180.50], EntityPainting['Painting'/133, l='MpServer', x=737.06, y=66.50, z=200.50], EntityClientPlayerMP['oOSpiderdogoO'/52337, l='MpServer', x=739.50, y=71.62, z=170.50], EntityOtherPlayerMP['Kusorai'/375, l='MpServer', x=793.34, y=63.00, z=50.16], EntitySquid['Squid'/30275, l='MpServer', x=759.50, y=47.00, z=171.41]]
    Retry entities: 68 total; [EntityPainting['Painting'/133, l='MpServer', x=737.06, y=66.50, z=200.50], EntityCreeper['Creeper'/50185, l='MpServer', x=805.50, y=27.00, z=136.50], EntityCreeper['Creeper'/45710, l='MpServer', x=746.56, y=20.00, z=158.00], EntityBat['Bat'/37266, l='MpServer', x=798.13, y=20.10, z=124.53], EntityCreeper['Creeper'/52630, l='MpServer', x=775.50, y=25.00, z=254.50], EntityWitch['Witch'/52631, l='MpServer', x=773.88, y=25.00, z=258.31], EntitySquid['Squid'/29851, l='MpServer', x=741.75, y=54.28, z=128.38], EntitySquid['Squid'/29856, l='MpServer', x=728.50, y=52.16, z=128.94], EntityItem['item.item.dyePowder.black'/34724, l='MpServer', x=781.25, y=42.13, z=127.25], EntityFish['Fish'/29607, l='MpServer', x=685.13, y=51.38, z=115.25], EntityCreeper['Creeper'/52520, l='MpServer', x=812.69, y=19.00, z=209.31], EntitySkeleton['Skeleton'/52521, l='MpServer', x=814.00, y=19.00, z=210.50], EntityZombie['Zombie'/181, l='MpServer', x=796.30, y=14.00, z=130.30], EntitySkeleton['Skeleton'/53302, l='MpServer', x=700.50, y=22.00, z=211.50], EntitySlime['Slime'/182, l='MpServer', x=799.63, y=28.00, z=136.63], EntitySkeleton['Skeleton'/53303, l='MpServer', x=702.50, y=22.00, z=212.50], EntitySkeleton['Skeleton'/53304, l='MpServer', x=699.50, y=22.00, z=210.50], EntityZombie['Zombie'/185, l='MpServer', x=785.97, y=15.00, z=222.53], EntityFish['Fish'/30139, l='MpServer', x=805.00, y=52.25, z=104.50], EntityZombie['Zombie'/52668, l='MpServer', x=783.50, y=23.00, z=132.50], EntityEnderman['Enderman'/52669, l='MpServer', x=745.69, y=27.00, z=238.00], EntityZombie['Zombie'/64, l='MpServer', x=691.75, y=20.00, z=142.25], EntityZombie['Zombie'/65, l='MpServer', x=696.30, y=11.00, z=195.70], EntitySkeleton['Skeleton'/52673, l='MpServer', x=738.50, y=32.00, z=142.50], EntityZombie['Zombie'/66, l='MpServer', x=696.30, y=11.00, z=195.60], EntityBat['Bat'/51650, l='MpServer', x=813.47, y=24.00, z=128.75], EntityBat['Bat'/43717, l='MpServer', x=798.66, y=27.45, z=148.31], EntityBat['Bat'/43720, l='MpServer', x=803.50, y=28.33, z=137.53], EntityZombie['Zombie'/74, l='MpServer', x=697.53, y=33.00, z=165.97], EntitySkeleton['Skeleton'/50510, l='MpServer', x=743.50, y=28.00, z=142.50], EntitySkeleton['Skeleton'/52562, l='MpServer', x=810.50, y=18.00, z=111.50], EntityCreeper['Creeper'/50774, l='MpServer', x=762.50, y=20.00, z=132.50], EntitySkeleton['Skeleton'/52695, l='MpServer', x=743.50, y=28.00, z=240.50], EntityCreeper['Creeper'/50775, l='MpServer', x=759.50, y=20.00, z=134.50], EntitySkeleton['Skeleton'/52696, l='MpServer', x=745.50, y=28.00, z=240.50], EntityCreeper['Creeper'/50776, l='MpServer', x=760.50, y=20.00, z=132.50], EntitySpider['Spider'/52441, l='MpServer', x=731.50, y=32.00, z=257.41], EntitySkeleton['Skeleton'/52697, l='MpServer', x=741.50, y=28.00, z=241.50], EntitySkeleton['Skeleton'/50777, l='MpServer', x=761.50, y=20.00, z=131.50], EntitySkeleton['Skeleton'/52698, l='MpServer', x=740.50, y=28.00, z=239.50], EntityEnderman['Enderman'/50778, l='MpServer', x=763.50, y=20.00, z=133.50], EntityZombie['Zombie'/218, l='MpServer', x=815.30, y=11.00, z=121.70], EntityWitch['Witch'/49626, l='MpServer', x=818.88, y=37.00, z=101.53], EntitySkeleton['Skeleton'/52699, l='MpServer', x=744.50, y=28.00, z=241.50], EntityEnderman['Enderman'/50779, l='MpServer', x=762.50, y=20.00, z=133.50], EntityZombie['Zombie'/219, l='MpServer', x=816.50, y=11.00, z=120.44], EntityCustomVillager['Custom Villager'/93, l='MpServer', x=721.50, y=64.00, z=124.72], EntitySpider['Spider'/52445, l='MpServer', x=733.03, y=32.00, z=260.59], EntityCustomVillager['Custom Villager'/94, l='MpServer', x=721.50, y=64.00, z=113.94], EntitySpider['Spider'/52446, l='MpServer', x=735.19, y=32.00, z=258.97], EntityCustomVillager['Custom Villager'/95, l='MpServer', x=734.22, y=64.00, z=124.63], EntityEnderman['Enderman'/50783, l='MpServer', x=740.50, y=32.00, z=141.50], EntitySpider['Spider'/52447, l='MpServer', x=739.72, y=33.00, z=261.56], EntityCustomVillager['Custom Villager'/97, l='MpServer', x=721.66, y=64.00, z=134.66], EntityCustomVillager['Custom Villager'/98, l='MpServer', x=734.50, y=64.00, z=133.94], EntityCustomVillager['Custom Villager'/99, l='MpServer', x=722.50, y=64.00, z=143.94], EntityCustomVillager['Custom Villager'/100, l='MpServer', x=734.50, y=64.00, z=147.28], EntityZombie['Zombie'/37348, l='MpServer', x=795.50, y=16.00, z=111.50], EntityCreeper['Creeper'/52592, l='MpServer', x=693.50, y=40.00, z=225.50], EntityCreeper['Creeper'/42480, l='MpServer', x=816.50, y=38.00, z=101.50], EntitySkeleton['Skeleton'/53619, l='MpServer', x=821.06, y=14.00, z=149.50], EntitySkeleton['Skeleton'/53620, l='MpServer', x=819.50, y=14.00, z=150.50], EntitySkeleton['Skeleton'/53621, l='MpServer', x=815.50, y=14.00, z=148.50], EntityZombie['Zombie'/42232, l='MpServer', x=795.53, y=20.00, z=122.75], EntityCreeper['Creeper'/52601, l='MpServer', x=666.50, y=28.00, z=145.50], EntityZombie['Zombie'/42233, l='MpServer', x=790.50, y=22.00, z=129.50], EntityCreeper['Creeper'/52602, l='MpServer', x=667.50, y=28.00, z=145.50], EntityBat['Bat'/45181, l='MpServer', x=784.44, y=12.00, z=148.56]]
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 261911544 bytes (249 MB) / 647028736 bytes (617 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 39 mods loaded, 39 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCHIJA  CustomLanPort{0.0.1} [CustomLanPort](minecraft.jar) 
    UCHIJA  mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) 
    UCHIJA  gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar) 
    UCHIJA  AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJA  arsmagica2{1.4.0.009} [Ars Magica 2](1.7.10_AM2-1.4.0.009.jar) 
    UCHIJA  lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) 
    UCHIJA  aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar) 
    UCHIJA  ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](Archimedes-Ships-Mod-1.7.10.jar) 
    UCHIJA  chocolateQuest{1.0} [Chocolate Quest](Better-Dungeons-Mod-1.7.10.jar) 
    UCHIJA  betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) 
    UCHIJA  BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar) 
    UCHIJA  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJA  Botania{r1.8-248} [Botania](Botania r1.8-248.jar) 
    UCHIJA  CarpentersBlocks{3.3.5} [Carpenter's Blocks](Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
    UCHIJA  cfm{3.4.8} [§9MrCrayfish's Furniture Mod](cfm-3.4.8-mc1.7.10.jar) 
    UCHIJA  BuildMod{v1.0} [Build Mod](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJA  CoroPets{v1.0} [CoroPets](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJA  CoroAI{v1.0} [CoroAI](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJA  ExtendedRenderer{v1.0} [Extended Renderer](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJA  ConfigMod{v1.0} [Extended Mod Config](coroutil-1.1.3 for MC v1.7.10.jar) 
    UCHIJA  meteors{2.13} [Falling Meteors](Falling-Meteors-Mod-1.7.10.jar) 
    UCHIJA  legendgear{2.b.2.1} [LegendGear 2](legendgear-1.7.10-2.b.2.1.jar) 
    UCHIJA  magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) 
    UCHIJA  MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UCHIJA  Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) 
    UCHIJA  Rediscovered{1.1} [Minecraft Rediscovered Mod](Rediscovered-1.7.10-1.1.jar) 
    UCHIJA  ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJA  Roguelike{1.4.4} [Roguelike Dungeons](roguelike-1.7.10-1.4.4.jar) 
    UCHIJA  AS_Ruins{14.7} [Ruins Spawning System](Ruins-1.7.10.jar) 
    UCHIJA  runicdungeons{1.1.6a} [Runic Dungeons](runicdungeons-1.1.6a.jar) 
    UCHIJA  gibby_enchanted{1.6} [Staffs and Wizards Mod](Staffs and Wizard Mod 1.7-1.7.10.jar) 
    UCHIJA  ctrades{1.3.2} [Custom Trades Mod](Trades-mc1.7.10-1.3.2.jar) 
    UCHIJA  TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJA  AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UCHIJA  weather2{v2.3.10} [Localized Weather & Storms](weather2-2.3.10 for MC v1.7.10.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.0' Renderer: 'AMD Radeon HD 7900 Series'
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7900 Series GL version 4.5.13431 Compatibility Profile Context 16.150.2211.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [John Smith Legacy 1.7.10 v1.2.24.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

It seems that it might be Meteor mod doing it after all? Judging from the top of the list, meteor shield from Falling Meteors is what's causing the crash for whatever reason. Is there any way to fix it? I don't want to get rid of falling meteors.
