### ISSUE TITLE
How do i get orespawn to not error?

### ISSUE THREAD

**Issue by koolkid1** [gildedgames/aether-issues#638]
---- Minecraft Crash Report ----
// Oops.

Time: 4/19/16 11:13 AM
Description: Initializing game

java.lang.IllegalArgumentException: ID is already registered: Ghost
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:90)
    at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
    at danger.orespawn.OreSpawnMain.make_some_more_things(OreSpawnMain.java:4571)
    at danger.orespawn.OreSpawnMain.preInit(OreSpawnMain.java:1839)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:90)
    at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
    at danger.orespawn.OreSpawnMain.make_some_more_things(OreSpawnMain.java:4571)
    at danger.orespawn.OreSpawnMain.preInit(OreSpawnMain.java:1839)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 190582944 bytes (181 MB) / 489299968 bytes (466 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 77 mods loaded, 68 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCH Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCH NotEnoughItems{1.0.3.74} [Not Enough Items](Not-Enough-Items-1.7.10.jar) 
    UCH se{0.4.1} [Super Enchants](minecraft.jar) 
    UCH OpenModsCore{0.6} [OpenModsCore](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) 
    UCH gilded-games-util{1.7.10-1.2} [Gilded Games Utility](gilded-games-util-1.7.10-1.9.jar) 
    UCH FLabsBF{4.3} [Better Furnaces]([1.7.10]Better_Furnaces_V4.3.jar) 
    UCH DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCH BuildCraft|Core{6.1.5} [BuildCraft](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCH BuildCraft|Builders{6.1.5} [BC Builders](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCH BuildCraft|Transport{6.1.5} [BC Transport](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCH BuildCraft|Silicon{6.1.5} [BC Silicon](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCH BuildCraft|Factory{6.1.5} [BC Factory](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCH BuildCraft|Energy{6.1.5} [BC Energy](_BuildCraft-Mod-Stable-1.7.10.jar) 
    UCH adminweapons{1.0} [Admin Weapons](adminweapons-v1-mc1.7.10.jar) 
    UCH aether{1.7.10-1.6} [Aether II](aether-1.7.10-1.6.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH thexfactor117_ascension{b1.2.3} [Ascension](Ascension-b1.2.3.jar) 
    UCH Backpack{2.0.1} [Backpack](Backpacks-Mod.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH BiblioCraft{1.7.3} [BiblioCraft](BiblioCraft-Mod-1.7.10.jar) 
    UCH CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCH chancecubes{1.7.10-1.6.2.72} [Chance Cubes](ChanceCubes-1.7.10-1.6.2.72.jar) 
    UCH EE3{0.3.507} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.507.jar) 
    UCH TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCH chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCH DeadlyWorld{1.0.2} [Deadly World](DeadlyWorld-1.7.10-1.0.2.jar) 
    UCH eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCH ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCH ExtraUtilities{1.2.4b} [Extra Utilities](extrautilities-1.2.4b.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCH Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCH headcrumbs{1.2.5} [Headcrumbs](Headcrumbs-Mod-1.7.10.jar) 
    UCH IC2{2.2.791-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UCH InventoryPets{1.4.0} [Inventory Pets](inventorypets-1.7.10-1.4.0-universal.jar) 
    UCH inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCH IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCH jaff{1.4.1_for_1.7.10} [Just a Few Fish](JustAFewFish-1.4.1_for_1.7.10.jar) 
    UCH legends{1.4} [Legends Mod](Legends Core-1.4.jar) 
    UCH lootplusplus{0.22_for_1.7} [Loot++](Loot++-0.22_for_1.7.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCH MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCH MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCH MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCH Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCH OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-268.jar) 
    UCH OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-512.jar) 
    UCE OreSpawn{1.7.10.20.3} [OreSpawn](orespawn-1.7.10-20.3.zip) 
    UCH PortalGun{4.0.0-beta-2} [PortalGun](Portal-Gun-Mod-1.7.10.jar) 
    UCH HeroSuits{1.2} [Project Superhuman](ProjectSuperhuman - v1.2 - 1.7.10.jar) 
    UCH RainbowWorld{1.0.0} [RainbowWorld](Rainbow World %281.7.10%29.jar) 
    UCH ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCH transformers{0.5.0} [Transformers Mod](Transformers-1.7.10-0.5.1.jar) 
    UCH lucky{5.1.0} [Lucky Block](z[1-7-10]_Lucky_Block_v5-1-0.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.91' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    CoFHCore: -[1.7.10]3.1.2-325
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    ThermalFoundation: -[1.7.10]1.2.3-112
    Mantle Environment: Environment healthy.
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    ThermalExpansion: -[1.7.10]4.1.2-240
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.91, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Collin1971** [comment]
You have an entity ID conflict and need to change Orespawn's. If it has a config, that's a good place to look.

**Comment by koolkid1** [comment]
I don't need ascension, that was the thingy

**Comment by koolkid1** [comment]
but one of my worlds is rip
