### ISSUE TITLE
What this?

### ISSUE THREAD

**Issue by iLefty** [gildedgames/aether-issues#649]
[15:11:09 INFO]: paxaXD[/78.81.206.65:54525] logged in with entity id 907531 at ([world] 1476.2169848543015, 5.0, 2135.087359385586)
[15:11:09 WARN]: java.io.IOException: Server returned HTTP response code: 500 for URL: http://www.gilded-games.com/aether/signatureUUID.php?name=71eb16c2e536433db61f4990657e0b73
[15:11:09 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
[15:11:09 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[15:11:09 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
[15:11:09 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
[15:11:09 WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[15:11:09 WARN]:        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[15:11:09 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
[15:11:09 WARN]:        at net.aetherteam.aether.Aether.readPage(Aether.java:610)
[15:11:09 WARN]:        at net.aetherteam.aether.donator.DonatorChoice.isDonator(DonatorChoice.java:73)
[15:11:09 WARN]:        at net.aetherteam.aether.player.PlayerTracker.onPlayerLogin(PlayerTracker.java:43)
[15:11:09 WARN]:        at net.aetherteam.aether.player.PlayerTracker.PlayerLoggedInEvent(PlayerTracker.java:28)
[15:11:09 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_PlayerTracker_PlayerLoggedInEvent_PlayerLoggedInEvent.invoke(.dynamic)
[15:11:09 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[15:11:09 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[15:11:09 WARN]:        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:572)
[15:11:09 WARN]:        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:243)
[15:11:09 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:200)
[15:11:09 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:475)
[15:11:09 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[15:11:09 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[15:11:09 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[15:11:09 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[15:11:09 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[15:11:09 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:11:09 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[15:11:09 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[15:11:09 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[15:11:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[15:11:09 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[15:11:09 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[15:11:09 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[15:11:09 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[15:11:09 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[15:11:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[15:11:09 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[15:11:09 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[15:11:09 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by jellysquid3** [comment]
It's responsible for determining whether or not you're a donator. We're working on resolving server issues related to it.

**Comment by jellysquid3** [comment]
We've resolved the server-side configuration issue.
