### ISSUE TITLE
[Aether 1.10.2] Game crashes after updating to new version.

### ISSUE THREAD

**Issue by tpapaj** [gildedgames/aether-issues#666]
Hello. There was an update that supposedly fixed some problems with new Aether 1.10.2.
I was playing first version of this mod, the file was AetherII-1.10.2-r1.git-c82b52e.jar
After the mod was updated to AetherII-1.10.2-r1.git-9f03aad.jar version, game crashes when trying to open world made with first 1.10.2 version.

Pastebin of crash report: http://pastebin.com/EkppyVYL

If it doesn't work, here's crash report directly:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 05.11.16 14:54
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.gildedgames.aether.common.world.dimensions.aether.island.logic.IslandSectorAccess.addSectorToMemory(IslandSectorAccess.java:287)
	at com.gildedgames.aether.common.world.dimensions.aether.island.logic.IslandSectorAccess.attemptToLoadSector(IslandSectorAccess.java:115)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.generateBiomes(BiomeProviderAether.java:81)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.func_76931_a(BiomeProviderAether.java:145)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.func_180300_a(BiomeProviderAether.java:57)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.func_180631_a(BiomeProviderAether.java:51)
	at com.gildedgames.aether.common.world.dimensions.aether.WorldProviderAether.getBiomeForCoords(WorldProviderAether.java:39)
	at net.minecraft.world.World.func_180494_b(World.java:142)
	at net.minecraft.entity.player.EntityPlayerMP.func_147098_j(EntityPlayerMP.java:395)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:372)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.gildedgames.aether.common.world.dimensions.aether.island.logic.IslandSectorAccess.addSectorToMemory(IslandSectorAccess.java:287)
	at com.gildedgames.aether.common.world.dimensions.aether.island.logic.IslandSectorAccess.attemptToLoadSector(IslandSectorAccess.java:115)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.generateBiomes(BiomeProviderAether.java:81)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.func_76931_a(BiomeProviderAether.java:145)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.func_180300_a(BiomeProviderAether.java:57)
	at com.gildedgames.aether.common.world.dimensions.aether.biomes.BiomeProviderAether.func_180631_a(BiomeProviderAether.java:51)
	at com.gildedgames.aether.common.world.dimensions.aether.WorldProviderAether.getBiomeForCoords(WorldProviderAether.java:39)
	at net.minecraft.world.World.func_180494_b(World.java:142)
	at net.minecraft.entity.player.EntityPlayerMP.func_147098_j(EntityPlayerMP.java:395)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 78
	Entity Name: ryder911
	Entity's Exact location: -135,34, 95,00, -114,65
	Entity's Block location: World: (-136,95,-115), Chunk: (at 8,5,13 in -9,-8; contains blocks -144,0,-128 to -129,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:372)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1eb58e61
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 306653024 bytes (292 MB) / 697827328 bytes (665 MB) up to 4250402816 bytes (4053 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms320M -Xmx4096M -Xmn128M
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2094 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2094.jar) 
	UCHIJAAAA	Forge{12.18.1.2094} [Minecraft Forge] (forge-1.10.2-12.18.1.2094.jar) 
	UCHIJAAAA	aether{1.10.2-r1} [Aether II] (AetherII-1.10.2-r1.git-9f03aad.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ryder911'/78, l='Aether1.10Main', x=-135,34, y=95,00, z=-114,65]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jellysquid3** [comment]
This issue tracker is not for the indev releases. To report an issue with indev releases, use our issue tracker at https://git.gildedgames.com/GildedGames/Aether-II/issues.
