### ISSUE TITLE
1.7.10 - Player unable to respawn after death - net.aetherteam.aether.player.PlayerAether.onRespawn

### ISSUE THREAD

**Issue by ProsperCraft** [gildedgames/aether-issues#674]
After death in the nether, player is unable to respawn.
Spawn is in tropicraft dim.

[net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension 34, does not exist
[16:50:40] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerRespawnEvent@7d18e94d:
java.lang.NullPointerException
        at net.minecraft.entity.player.EntityPlayer.func_71056_a(EntityPlayer.java:1501) ~[yz.class:?]
        at net.aetherteam.aether.player.PlayerAether.onRespawn(PlayerAether.java:508) ~[PlayerAether.class:?]
        at com.gildedgames.util.player.common.PlayerEventHandler.onRespawn(PlayerEventHandler.java:160) ~[PlayerEventHandler.class:?]
Console error
https://gist.github.com/ProsperCraft/1fb43f92d726f2162294af9a7cae9260

Playerfile
[c5e6f5af-4048-4a21-a231-44d041e6b2b4.zip](https://github.com/gildedgames/aether-issues/files/644916/c5e6f5af-4048-4a21-a231-44d041e6b2b4.zip)

FML log
https://gist.github.com/ProsperCraft/7e7244ea109afb3842b4fa4e89cacfa0

**Comment by ProsperCraft** [comment]
Don't now if you can do anything about this so closing it.
