### ISSUE TITLE
World Doesn't want to load my world.

### ISSUE THREAD

**Issue by ajhiitree** [gildedgames/aether-issues#724]
I'm on 1.12.2, latest version of forge and I have the latest version of orbisapi as well but when I try to load my singleplayer worlds they get stuck after loading world and it just says 0%
This is the paste of my latest.log:
https://pastebin.com/dSXPJH4X
And of my debug.log:
https://pastebin.com/T9if9tUw

**Comment by MechanosG** [comment]
I believe I'm getting the same error.  Wanted to test out Aether II in 1.12.2 in a modpack, went to create a new world, and it stops just before creating the world, with 0% on the screen.  This is what shows up in the logs.

[14:58:44] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Aether II (aether)

Caused by: java.lang.RuntimeException: Failed to load Blueprint Data: outpost_a.blueprint
	at com.gildedgames.aether.common.registry.content.BlueprintsAether.loadData(BlueprintsAether.java:77) ~[BlueprintsAether.class:?]
	at com.gildedgames.aether.common.registry.content.BlueprintsAether.load(BlueprintsAether.java:88) ~[BlueprintsAether.class:?]
	at com.gildedgames.aether.common.registry.ContentRegistry.onStartProjectManager(ContentRegistry.java:190) ~[ContentRegistry.class:?]
	at com.gildedgames.orbis_api.OrbisServices.lambda$startProjectManager$0(OrbisServices.java:502) ~[OrbisServices.class:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_171]
	at com.gildedgames.orbis_api.OrbisServices.startProjectManager(OrbisServices.java:502) ~[OrbisServices.class:?]
	at com.gildedgames.orbis_api.OrbisServices.verifyProjectManagerStarted(OrbisServices.java:545) ~[OrbisServices.class:?]
	at com.gildedgames.aether.common.util.helpers.PerfHelper.measure(PerfHelper.java:11) ~[PerfHelper.class:?]
	at com.gildedgames.aether.common.registry.ContentRegistry.onServerAboutToStart(ContentRegistry.java:98) ~[ContentRegistry.class:?]
	at com.gildedgames.aether.common.CommonProxy.onServerAboutToStart(CommonProxy.java:95) ~[CommonProxy.class:?]
	at com.gildedgames.aether.common.AetherCore.onServerAboutToStart(AetherCore.java:101) ~[AetherCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) ~[forge-1.12.2-14.23.5.2775.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) ~[forge-1.12.2-14.23.5.2775.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) ~[forge-1.12.2-14.23.5.2775.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:864) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292) [FMLCommonHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:155) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[14:58:44] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[14:58:44] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[14:58:44] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds

**Comment by ajhiitree** [comment]
Nevermind I managed to fix it by downloading an older version of orbis

**Comment by MechanosG** [comment]
Which version?  Just 1 version back or a specific one?

**Comment by MechanosG** [comment]
Yep, confirmed.  Going back 1 version in orbis fixes the problem.  Thanks for posting that.
